### ISSUE TITLE
webpack.config.js

### ISSUE THREAD

**Issue by pingan1927** [liubin1023/MemberMobileSystem#1]
```
config.postcss.push(pxtorem({
      rootValue: 100,
      propWhiteList: [],
      selectorBlackList: [/^html$/, /^\.ant-/, /^\.github-/, /^\.gh-/],
    }));
```

**Comment by pingan1927** [comment]
页面中viewport的动态设置请参考这个下
https://github.com/ant-design/ant-design-mobile/blob/master/site/mobile/static/template.html#L7

**Comment by liubin1023** [comment]
@pingan1927 
webpack https://github.com/liubin1023/MemberMobileSystem/blob/master/webpack.config.js#L39-#L45

html
https://github.com/liubin1023/MemberMobileSystem/blob/master/src/index.html#L13

想到的配置都加了，但是字体还是很大，高清方案还是有问题...

**Comment by ghost** [comment]
我用了这个库 https://github.com/amfe/lib-flexible 
`antd-mobile  Input placeholder` 的字体非常大

**Comment by liubin1023** [comment]
https://github.com/ant-design/ant-design-mobile/issues/454

**Comment by markzhai** [comment]
@liubin1023 
最后是怎么弄好的呢？那三个东西都配了...但是 Web 上各种尺寸还是2倍大小

**Comment by liubin1023** [comment]
@markzhai 就是链接的那3条，我是忘了做最后一条导致的

**Comment by markzhai** [comment]
@liubin1023 搞定了。。。是 webpack 解析 less 的时候没有把 postcss 加进去。。谢谢
